### ISSUE TITLE
Handling multiple module repositories containing modules with the same name

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#194]
This might relate to #160 

If you include multiple module repositories in an image YAML, and reference a module name that occurs in both repositories, which repo wins? it's not clear that this is a defined situation and you will get the same behaviour every time.

**Comment by dbecvarik** [comment]
For now this is undefined behavior (especially even if module version match). 
My best preference would be to throw error here and quit as I don't want to implement/explain error prone modules priority.

**Comment by rcernich** [comment]
I think we generate a warning at least, but I think we should fail, possibly adding a --ignore-duplicate-modules flag.  Versioning is a slightly different matter, because if there are two distinct modules, and versions are specified, a duplicate situation would only occur if they were the same id:version.

**Comment by dbecvarik** [comment]
I'm ok with warning in the case of duplicit module without version specification - but this should not be happening as best practices and we should not allow this in our repos. 
But if we find duplicit id:version pair I think that we should just fail in every case and ask developer to fix the repo.

IIn next concreate version, I would just go with warning about this and saying, that next version will fail, so we can give some grace period for images to migrate.

**Comment by rcernich** [comment]
Sounds good to me.  Best practices would mitigate this, but there's no way to tell if you're adhering to best practices without checks.  Fail early!

**Comment by goldmann** [comment]
I think we are failing right now, but this needs to be investigated.

* Two repos with same modules should produce a potential warning. It could be ignored in local development phase when you explicitly override the module, so this would be expected.
* When a module name and version match, build should fail, because we do not have a way to specify order of repositories.
