### ISSUE TITLE
Use rpm -V to verify if the package is installed

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#289]
Probably using `-V` instead of `-q` makes more sense.

/CC @jmtd

**Comment by jmtd** [comment]
In terms of return code, they behave the same, so both would work in the place we use it (to ensure that yum actually successfully installed the packages)

the difference is -V would catch files from the installed RPMs not matching what RPM thinks they should be. So it would potentially catch a source of errors. I think it would result in slightly longer builds, since it does more work than -q, but perhaps not significantly so (measureably for a big package such as openjdk-1.8.0-openjdk-devel on my laptop/VM/containers, but still sub-second)

Is there any situation where an RPM postinst script would modify a file that was checksummed in the RPM? I'm guessing all conf files are excluded.
