### ISSUE TITLE
the git "ref:" argument should accept a valid git reference

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#618]
**Describe the bug**

cekit permits specifying a git ref for a module, but this does not translate into a git ref underneath, but must actually be a tag or branch name (valid argument to `git clone -b`). It would be nicer if this could be a real git ref (e.g. be123a80c5497a595e2a997a0f1dbe14c9e3442e)

**To reproduce**

Attempt to set the git ref for an external module to a ref that is not a branch or tag name.

**Expected behavior**

Remote repository cloned and local branch set up to reference the ref  specified, even if it was a sha1-id.

 - CEKit version: 3.4.0

**Comment by goldmann** [comment]
I'm looking at this now. Changing this to accept any ref is very simple, but the only thing that bothers me a bit is that it is suboptimal: we need to clone the whole repository first so that locally we have all information and only then checkout a specific ref. For large repositories it may be an issue making the run slower, but I guess the feature to use any ref is probably worth it.
