### ISSUE TITLE
documentation note leads to 404

### ISSUE THREAD

**Issue by mattf** [cekit/cekit#679]
go to https://docs.cekit.io/en/2.2.7/build.html

you find "Note - You are not reading the most recent version of this documentation. 3.8.0 is the latest version available."

"3.8.0" is a link to https://docs.cekit.io/en/3.8.0/build.html, which is 404 in the 3.8.0 documentation

**Comment by goldmann** [comment]
Thanks for the report!

Unfortunately I don't think there is a way to fix it. Message you see on the top is generated by readthedocs and it tries to be smart at linking to latest version. Unfortunately documentation can change across versions and this leads to link with 404's, because documentation was rewritten and some pages are moved around.

This is what happened in this case. As long as I would like to fix it, I don't see how it could be done and thus I'll close this ticket.
