### ISSUE TITLE
When using the --verbose flag also set the debug flag for rhpkg command

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#853]
**Describe the solution you'd like**
It is useful to debug rhpkg issues, sometimes the error message might not he enough to understand what is happening.

**Additional context**
We hit a issue recently that the rhpkg returns just "None"  in the error message, e.g.:

```
ERROR Command '['/usr/bin/rhpkg', '--user', ...
...
Returned non-zero exit status 1. Command stdout is 'None' with stderr 'None'
```

**Comment by rnc** [comment]
Thats a good idea! Wonder if any other executed subcommands should also be run with verbose?

**Comment by rnc** [comment]
rhpkg has
```
  --verbose, -v         Run with verbose debug output
  --debug, -d           Run with debug output
  -q                    Run quietly only displaying errors
```

Other tools:

* buildah / podman
```
--log-level string                     The log level to be used. Either "trace", "debug", "info", "warn", "error", "fatal", or "panic". (default "warn")
```

* brew / koji
``` 
  -d, --debug           show debug output
```

**Comment by spolti** [comment]
> Thats a good idea! Wonder if any other executed subcommands should also be run with verbose?

+1 from me.

We could, for each other component, use the most verbosity output possible.

**Comment by goldmann** [comment]
I wouldn't use the most verbose settings because of the reason @rnc mentioned. I think we need to balance this.

**Comment by rnc** [comment]
> I wouldn't use the most verbose settings because of the reason @rnc mentioned. I think we need to balance this.

We almost need a trace option or some other form that configures debug on the child processes. Generally I think this **shouldn't** be needed and I believe this issue came about from #857 - where there was a missing debug print in https://github.com/cekit/cekit/pull/857/files#diff-53fb5968a14cd97636475ff271beedac8d436a8e4a42bbd44235de8e37307977R236 and further the subprocess handling wasn't using the unified wrapper https://github.com/cekit/cekit/pull/857/files#diff-5da4de3277fb6db65150a2b3ad22fccd770faa49b2ab8a6964c4e4c14837a613R208
