### ISSUE TITLE
Opt-out from package manager cleanup 

### ISSUE THREAD

**Issue by ricardozanini** [cekit/cekit#886]
**Describe the solution you'd like**
Hi! Is it possible to opt-out of the package manager metadata clean up? I can manage this by myself in a custom module.

**Additional context**
I'm trying to produce [reproducible builds for my images](https://reproducible-builds.org/) and this package manager cleanup that Cekit does at the end:

```Dockerfile
    # Clear package manager metadata
    RUN microdnf clean all && [ ! -d /var/cache/yum ] || rm -rf /var/cache/yum
```

Adds the `rpm` and `microdnf` cache and history I cleared before. These files contain non-deterministic files with timestamps and random UUID, making a reproducible build impossible.

I'm also opened to suggestions and how to approach this.

**Comment by rnc** [comment]
Related to this is https://github.com/cekit/cekit/issues/849 where they wanted package manager cleanup after each install in each layer. 

There is also the point that I suspect `/var/cache/yum` might be outdated now - it should be (or be as well) `/var/cache/dnf`. And the `if` test is somewhat redundant with `rm -rf`. 

In terms of package manager configuration - perhaps it could be more flexible offering the current choice (i.e. cleanup at end), cleanup per module, or no cleanup ?

**Comment by ricardozanini** [comment]
I'd vote for no cleanup at all and let the module or image handle that. I was maintaining some old codebase that was running the clean up in a "clean up" module. :) 

I understand that the tool shouldn't be opinionated to this point.

**Comment by rnc** [comment]
I don't think no cleanup is an option - that would be a rather surprising change to many users and effectively a 'breaking' change. However, I understand some users want more flexibility and manual control hence looking at configuration instead. 

@goldmann - thoughts?

**Comment by goldmann** [comment]
I'm with you, @rnc. I think cleaning up by default is a sane default. If it would be possible to not make it as part of a switch, then that would be nice. But I imagine this is all-or-nothing option everything cleaned up or nothing cleaned up and left to module developer to tackle this.

**Comment by ricardozanini** [comment]
+1 to add the on/off option for clean up.

**Comment by jmtd** [comment]
I think the package management abstraction in `template.jinja` needs a little clean-up. At least with `manager: microdnf`, there's a `clean all` stage added to the end of each `install` as well. Thinking about this from a few different perspectives

 * I think supporting reproducible builds is a very good idea
 * if using layer squashing, from a speed perspective, doing all those `clean`s except the last are just costing build time
 * on the other hand if we are NOT using layer squashing then having the `clean` in is a good idea
 * the cleans after the installs don't perform the additional `rm -rf /var/cache/yum`
 * @ricardozanini 's problem is that the `clean all` command *creates* data (in `/var/lib/dnf` and `/var/lib/rpm`) that is not otherwise cleaned up: simply adding those directories to the list that is removed at the very end would be the simplest way to address the immediate problem (if it's safe for subsequent DNF/RPM operation in downstream images)

So I would propose extending the remove-at-end to cover the additional directories as a fast fix, and then look at whether we vary whether we clean up (and where we clean up) under what circumstances: different defaults for whether squashing or not? etc

**Comment by ricardozanini** [comment]
Very nice proposal, @jmtd!

**Comment by rnc** [comment]
@jmtd Nice write up! Thinking on this further - having `clean all` isn't quite right for apt-get (although harmless according to https://www.networkworld.com/article/968090/cleaning-up-with-apt-get.html ). We do probably need to add the appropriate directories for apt for deletion.

I hadn't realised that `/var/lib/dnf` was also being created/changed and so would agree with removing that. A question though - if the clean **only** operates with those /var/cache and /var/lib directories then do we need to run `dnf clean all` versus just using `rm -rf /var/cache/dnf /var/lib/dnf` ?

**Comment by jmtd** [comment]
> having clean all isn't quite right for apt-get (although harmless according to https://www.networkworld.com/article/968090/cleaning-up-with-apt-get.html ). We do probably need to add the appropriate directories for apt for deletion.

100% . I was thinking of taking a closer look at the apt case when I look at packaging cekit for Debian.

> A question though - if the clean only operates with those /var/cache and /var/lib directories then do we need to run dnf clean all versus just using rm -rf

I'm not sure what else it does (if anything). Good Q. need to check

> (and for that matter is checking for the directory existing needed either ) ?

quite right, it isn't needed!

**Comment by jmtd** [comment]
`microdnf clean` on ubi9 modifies the following

```
FILE                                   SIZE
/etc/yum.repos.d/redhat.repo           0
/var/cache/yum                         0
/var/cache/yum/lock                    0
/var/lib/dnf                           148K
/var/lib/dnf/history.sqlite            116K
/var/lib/dnf/history.sqlite-shm        32K
/var/lib/dnf/history.sqlite-wal        0
```

The repo change can be ignored, that will be checking entitlements. You are right that we can skip `clean` and just blast those two directories.

Performing a package install and remove (`microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y tar` followed by `RUN microdnf remove -y tar`) also touches `/var/lib/rpm`. So I think `/var/lib/rpm`, `/var/cache/yum` and `/var/lib/dnf` cover all bases for UBI9/microdnf, at least.

**Comment by ricardozanini** [comment]
@jmtd I've got to the same conclusion, my clean script was ditching  `/var/lib/rpm`, `/var/cache/yum`, and `/var/lib/dnf`. It will break the manager's history but it won't matter since after the image is built we won't install anything on it. New layers can be added and run the installation procedure to restore the history for that given layer, correct?

**Comment by jmtd** [comment]
> New layers can be added and run the installation procedure to restore the history for that given layer, correct?

Yes; subsequent `microdnf install` commands work fine. There might be a difference  in behaviour:  for me right now, a simple `microdnf install tar` on top of the ubi-minimal image just installs `tar`. If I first remove those directories, it also updates a bunch of other packages: I guess, because the newly-downloaded metadata only references newer versions than what is installed in the ubi-minimal image.

**Comment by jmtd** [comment]
I've updated the PR to reflect these findings

**Comment by jmtd** [comment]
Relevant paths for Debian are `/var/lib/dpkg`,`/var/lib/apt`, `/var/log/apt`, `/var/cache/apt`, `/var/log/dpkg.log`
